<?php

namespace Database\Seeders;

use App\Models\Tag;
use Illuminate\Database\Seeder;

class TagSeeder extends Seeder
{
    public function run(): void
    {
        $tags = [
            'Cosmology',
            'Astronomy',
            'Space Exploration',
            'Black Holes',
            'Galaxies',
            'Astrophysics',
            'Cosmic Wonders',
            'Stellar Phenomena',
            'Exoplanets',
            'Dark Matter',
            'Celestial Bodies',
            'Nebulas',
            'Space Mysteries',
            'Cosmic Voyage',
            'Star Formation',
            'Supernovae',
            'Hubble Telescope',
            'Cosmic Radiation',
            'Milky Way',
            'Space Technology',
            'Cosmic Journey',
            'Planetary Exploration',
            'Astronomical Observations',
            'Outer Space',
            'Solar System',
            'Astro Photography',
            'Interstellar Travel',
            'Astronomy Facts',
            'Astrobiology',
            'Space Time',
            'Astro Engineering',
            'Extraterrestrial Life',
            'Cosmic Events',
            'Astronomy Club',
            'Cosmic Research',
            'Space Discoveries',
            'Astronomy Education',
            'Cosmic Phenomena',
            'Orbital Mechanics',
            'Space Astronomy',
            'Cosmic Journey',
            'Astro Cosmos',
            'Telescope Views',
            'Astro Exploration',
            'Cosmic Questions',
            'Galactic Wonders',
            'Astronomy News',
            'Astro Spectroscopy',
            'Stargazers',
            'Deep Space',
            'Astro Physics',
            'Cosmic Spectacles',
            'SpaceX',
            'Astronomy Talks',
            'Astro Geeks',
            'Star Clusters',
            'Astronomy Lovers',
            'Cosmic Discoveries',
            'Space Research',
            'Astro Universe',
            'Astronomy Photos',
            'Exploring Cosmos',
            'Cosmic Frontiers',
            'Planetary Systems',
            'Galactic Exploration',
            'Astro Cosmology',
            'Astronomy Forum',
            'Cosmic Mysteries',
            'Space Observatories',
            'Astronomy 101',
            'Astro Innovations',
            'Astro Data',
            'Astro Curiosity',
            'Astro Imaging',
            'Cosmic Wonderland',
            'Astro Discoveries',
            'Cosmic Jewels',
            'Astronomy Talk',
            'Astro Fascination',
            'Cosmic Realms',
            'Stellar Nurseries',
            'Astronomy Podcasts',
            'Cosmic Adventures',
            'Astronomy Books',
            'Astro Planetarium',
            'Cosmic Awe',
            'Starry Nights',
            'Astro Teaching',
            'Cosmic Explorers',
            'Astronomy Enthusiast',
            'Astro Unveilings',
            'Celestial Wonders',
            'Astronomy Magazines',
            'Astro Community',
            'Space Telescopes',
            'Cosmic Phenomenon',
            'Astronomy Art',
            'Astro Wonderment',
            'Space Adventures',
            'Cosmic Junction',
            'Programming',
            'Software Development',
            'Computer Science',
            'Cybersecurity',
            'Artificial Intelligence',
            'Machine Learning',
            'Web Development',
            'Data Science',
            'Hardware',
            'Tech Innovation',
            'Coding Life',
            'Tech News',
            'Software Engineering',
            'Computer Hardware',
            'Programming Languages',
            'AI Innovation',
            'Cyber Defense',
            'Web Development Trends',
            'Data Analytics',
            'Tech Startups',
            'Code Lovers',
            'Tech Gurus',
            'Open Source',
            'Computer Programming',
            'IoT',
            'Software Testing',
            'Algorithm Design',
            'IT Infrastructure',
            'Cloud Computing',
            'Machine Vision',
            'Cyber Threats',
            'Front End Development',
            'Back End Development',
            'Computer Security',
            'Programming Skills',
            'DevOps',
            'Robotics',
            'Blockchain',
            'Deep Learning',
            'IT Consulting',
            'Computer Networks',
            'Data Mining',
            'Tech Community',
            'Mobile App Development',
            'Code Review',
            'Game Development',
            'Tech Trends',
            'Programming Tips',
            'Software Architecture',
            'Digital Transformation',
            'Tech Industry',
            'AI Research',
            'Cyber Security Awareness',
            'Tech Leadership',
            'Coding Academy',
            'IoT Innovation',
            'Web Design',
            'Computer Engineering',
            'Quantum Computing',
            'Tech Policy',
            'Cloud Services',
            'Data Privacy',
            'Software Updates',
            'Tech Geek',
            'Hacker Community',
            'Tech For Good',
            'Programming Challenges',
            'Software Solutions',
            'Tech Entrepreneurs',
            'Dev Community',
            'AI Applications',
            'Coding Bootcamp',
            'Tech Savvy',
            'Cyber Security Experts',
            'Data Visualization',
            'Technology Innovation',
            'AR and VR',
            'IoT Security',
            'Tech Business',
            'Bioinformatics',
            'Tech Consultancy',
            'IT Services',
            'Tech Skills',
            'Innovative Tech',
            'Tech Ethics',
            'Code Crafting',
            'Tech Job Market',
            'Future Tech',
            'Tech Diversity',
            'Digital Skills',
            'Tech Hackathons',
            'Coding Culture',
            'Tech Community',
            'Software Quality',
            'Tech Networking',
            'Tech Startups',
            'AI in Business',
            'Tech Support',
            'Big Data',
            'Tech Education',
            'Science Facts',
            'Scientific Research',
            'STEM',
            'Biology',
            'Chemistry',
            'Physics',
            'Environmental Science',
            'Scientific Discovery',
            'Earth Sciences',
            'Medical Research',
            'Laboratory Life',
            'Climate Change',
            'Genetics',
            'Particle Physics',
            'Science Education',
            'Research Innovation',
            'Scientific Breakthroughs',
            'Microbiology',
            'Chemical Reactions',
            'Physics Phenomena',
            'Environmental Sustainability',
            'Biotechnology',
            'Ecology',
            'Astronomy Research',
            'Scientific Method',
            'Neuroscience',
            'Geology',
            'Botany',
            'Zoology',
            'Science News',
            'Science Communication',
            'Scientific Community',
            'Health Science',
            'Science Journals',
            'Research Discovery',
            'Science Technology',
            'Science Innovation',
            'Science Exploration',
            'Laboratory Research',
            'Science Careers',
            'STEM Education',
            'Chemistry Lab',
            'Science Enthusiast',
            'Scientific Experiments',
            'Natural Sciences',
            'Science Advancements',
            'Science For Good',
            'Science Books',
            'Science Magazines',
            'Citizen Science',
            'Science History',
            'Science Talks',
            'Science Forum',
            'Science Podcasts',
            'Science Awards',
            'Science Ethics',
            'Science Museums',
            'Science Curiosity',
            'Science Outreach',
            'Science Journalism',
            'Science Policy',
            'Science Impact',
            'Science Society',
            'Science Inspiration',
            'Science Discovery',
            'Science Explained',
            'Science Achievements',
            'Science Frontiers',
            'Science Wonder',
            'Science Researcher',
            'Science Lab Life',
            'Science Inquiry',
            'Science Innovators',
            'Science Enigma',
            'Science Quest',
            'Science Enlightenment',
            'Science Quest',
            'Science Education',
            'Science Professionals',
            'Science Community',
            'Science Conferences',
            'Science Future',
            'Science Impact',
            'Science Majors',
            'Science Insights',
            'Science Explorers',
            'Science Trivia',
            'Science Wonderland',
            'Science Universe',
            'Science Horizons',
            'Science Adventures',
            'Science Mindset',
            'Science Solutions',
            'Science Influence',
            'Science Frontlines',
            'Science Vision',
            'Science Fusion',
            'Science Spirit',
            'Science Trailblazers',
            'Science Journey',
        ];

        foreach ($tags as $tag) {
            Tag::create([
                'name' => $tag,
            ]);
        }
    }
}
